import {IAsyncCall} from '~Root/types';

export const INITIALIZE_AUTH_REQUESTED = 'INITIALIZE_AUTH/REQUESTED';
export const INITIALIZE_AUTH_SUCCESS = 'INITIALIZE_AUTH/SUCCESS';
export const INITIALIZE_AUTH_FAILURE = 'INITIALIZE_AUTH/FAILURE';

export const ASYNC_INITIALIZE_AUTH: IAsyncCall = {
  REQUESTED: INITIALIZE_AUTH_REQUESTED,
  SUCCESS: INITIALIZE_AUTH_SUCCESS,
  FAILURE: INITIALIZE_AUTH_FAILURE,
};

export const LOGOUT = 'LOGOUT';

export const COUNT_DOWN_REQUESTED = 'COUNT_DOWN/REQUESTED';
export const COUNT_DOWN_SUCCESS = 'COUNT_DOWN/SUCCESS';
export const COUNT_DOWN_FAILURE = 'COUNT_DOWN/FAILURE';

export const SET_PROGRESS = 'SET_PROGRESS/SET';
export const CLEAR_PROGRESS = 'CLEAR_PROGRESS/CLEAR';
