export const GET_NETWORK_CONNECTION_LIST_REQUESTED = 'GET_NETWORK_CONNECTION_LIST/REQUESTED';
export const GET_NETWORK_CONNECTION_LIST_SUCCESS = 'GET_NETWORK_CONNECTION_LIST/SUCCESS';
export const GET_NETWORK_CONNECTION_LIST_FAILURE = 'GET_NETWORK_CONNECTION_LIST/FAILURE';

export const ON_INVITE_USER_REQUESTED = 'ON_INVITE_USER/REQUESTED';
export const ON_INVITE_USER_SUCCESS = 'ON_INVITE_USER/SUCCESS';
export const ON_INVITE_USER_FAILURE = 'ON_INVITE_USER/FAILURE';

export const REMOVE_NETWORK_CONNECTION_REQUESTED = 'REMOVE_NETWORK_CONNECTION/REQUESTED';
export const REMOVE_NETWORK_CONNECTION_SUCCESS = 'REMOVE_NETWORK_CONNECTION/SUCCESS';
export const REMOVE_NETWORK_CONNECTION_FAILURE = 'REMOVE_NETWORK_CONNECTION/FAILURE';
