export const GET_CREDENTIAL_REQUESTED = 'GET_CREDENTIAL/REQUESTED';
export const GET_CREDENTIAL_SUCCESS = 'GET_CREDENTIAL/SUCCESS';
export const GET_CREDENTIAL_FAILURE = 'GET_CREDENTIAL/FAILURE';

export const SET_PUBNUB_MESSAGE = 'PUBNUB_MESSAGE/SET';
