export const INITIALIZE_APP = 'INITIALIZE_APP';
export const INITIALIZE_APP_SUCCESS = 'INITIALIZE_APP_SUCCESS';
export const INITIALIZE_APP_FAILURE = 'INITIALIZE_APP_FAILURE';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
