export const USER_INFO_REQUESTED = 'USER_INFO/REQUESTED';
export const USER_INFO_SUCCESS = 'USER_INFO/SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO/FAILURE';

export const UPDATE_USER_IN_APP_STATUS_REQUESTED = 'UPDATE_USER_IN_APP_STATUS/REQUESTED';
export const UPDATE_USER_IN_APP_STATUS_SUCCESS = 'UPDATE_USER_IN_APP_STATUS/SUCCESS';
export const UPDATE_USER_IN_APP_STATUS_FAILURE = 'UPDATE_USER_IN_APP_STATUS/FAILURE';

export const UPDATE_USER_AVATAR_REQUESTED = 'UPDATE_USER_AVATAR/REQUESTED';
export const UPDATE_USER_AVATAR_SUCCESS = 'UPDATE_USER_AVATAR/SUCCESS';
export const UPDATE_USER_AVATAR_FAILURE = 'UPDATE_USER_AVATAR/FAILURE';

export const UPDATE_USER_PROFILE_REQUESTED = 'UPDATE_USER_PROFILE/REQUESTED';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE/SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE/FAILURE';

export const SET_USER_INDUSTRY = 'USER_INDUSTRY/SET';
export const DELETE_DATA_INDUSTRY = 'DELETE_INDUSTRY_SELECTED/SET';
