import {IAsyncCall, ISetAsyncCall} from '~Root/types';

export const USER_INFO_REQUESTED = 'USER_INFO/REQUESTED';
export const USER_INFO_SUCCESS = 'USER_INFO/SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO/FAILURE';

export const ASYNC_USER_INFO: IAsyncCall = {
  REQUESTED: USER_INFO_REQUESTED,
  SUCCESS: USER_INFO_SUCCESS,
  FAILURE: USER_INFO_FAILURE,
};

export const UPDATE_USER_PROFILE_REQUESTED = 'UPDATE_USER_PROFILE/REQUESTED';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE/SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE/FAILURE';

export const SET_DATA_USER_INFO = 'DATA_USER_INFO/SET';
export const ASYNC_SET_DATA_USER_INFO: ISetAsyncCall = {
  SET: SET_DATA_USER_INFO,
};

export const ON_CHANGE_RESPONDER = 'CHANGE_RESPONDER/ON';
export const ASYNC_ON_CHANGE_RESPONDER: ISetAsyncCall = {
  SET: ON_CHANGE_RESPONDER,
};

export const ON_CHANGE_INTRODUCER = 'CHANGE_INTRODUCER/ON';
export const ASYNC_ON_CHANGE_INTRODUCER: ISetAsyncCall = {
  SET: ON_CHANGE_INTRODUCER,
};

export const ON_REVOKE_INVITE = 'REVOKE_INVITE/ON';
export const ASYNC_ON_REVOKE_INVITE: ISetAsyncCall = {
  SET: ON_REVOKE_INVITE,
};

export const SET_USER_PROFILE = 'USER_PROFILE/SET';
export const ASYNC_SET_USER_PROFILE: ISetAsyncCall = {
  SET: SET_USER_PROFILE,
};

export const SET_USER_PROFILE_REFER = 'USER_PROFILE_REFER/SET';
export const ASYNC_SET_USER_PROFILE_REFER: ISetAsyncCall = {
  SET: SET_USER_PROFILE_REFER,
};

export const SET_USER_PROFILE_AVATAR = 'USER_PROFILE_AVATAR/SET';
export const ASYNC_SET_USER_PROFILE_AVATAR: ISetAsyncCall = {
  SET: SET_USER_PROFILE_AVATAR,
};
export const SET_USER_PROFILE_TEMP = 'USER_PROFILE_TEMP/SET';

export const SET_USER_INDUSTRY = 'USER_INDUSTRY/SET';
export const DELETE_DATA_INDUSTRY = 'DELETE_INDUSTRY_SELECTED/SET';

export const GET_ASK_RESPONDER_REQUESTED = 'GET_ASK_RESPONDER/REQUESTED';
export const GET_ASK_RESPONDER_SUCCESS = 'GET_ASK_RESPONDER/SUCCESS';
export const GET_ASK_RESPONDER_FAILURE = 'GET_ASK_RESPONDER/FAILURE';

export const GET_ASK_INTRODUCER_REQUESTED = 'GET_ASK_INTRODUCER/REQUESTED';
export const GET_ASK_INTRODUCER_SUCCESS = 'GET_ASK_INTRODUCER/SUCCESS';
export const GET_ASK_INTRODUCER_FAILURE = 'GET_ASK_INTRODUCER/FAILURE';

export const GET_TAG_REQUESTED = 'GET_TAG/REQUESTED';
export const GET_TAG_SUCCESS = 'GET_TAG/SUCCESS';
export const GET_TAG_FAILURE = 'GET_TAG/FAILURE';

export const FILTER_DATA_TAG = 'DATA_TAG/FILTER';
export const SET_TAG_SELECTED = 'TAG_SELECTED/SET';

export const DELETE_TAG = 'DELETE_TAG/SET';
export const CLEAR_FEEDBACK = 'FEEDBACK/CLEAR';
