export const USER_INFO_REQUESTED = 'USER_INFO/REQUESTED';
export const USER_INFO_SUCCESS = 'USER_INFO/SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO/FAILURE';

export const UPDATE_USER_IN_APP_STATUS_REQUESTED = 'UPDATE_USER_IN_APP_STATUS/REQUESTED';
export const UPDATE_USER_IN_APP_STATUS_SUCCESS = 'UPDATE_USER_IN_APP_STATUS/SUCCESS';
export const UPDATE_USER_IN_APP_STATUS_FAILURE = 'UPDATE_USER_IN_APP_STATUS/FAILURE';

export const SET_USER_INDUSTRY = 'USER_INDUSTRY/SET';
export const DELETE_DATA_INDUSTRY = 'DELETE_INDUSTRY_SELECTED/SET';
