import {IAsyncCall, IModalAsyncCall, ISetAsyncCall} from '~Root/types';

export const CONTACT_REQUESTED = 'CONTACT/REQUESTED';
export const CONTACT_SUCCESS = 'CONTACT/SUCCESS';
export const CONTACT_FAILURE = 'CONTACT/FAILURE';

export const ASYNC_CONTACT: IAsyncCall = {
  REQUESTED: CONTACT_REQUESTED,
  SUCCESS: CONTACT_SUCCESS,
  FAILURE: CONTACT_FAILURE,
};

export const SET_CONTACT = 'SET_CONTACT/SET';
export const ASYNC_SET_CONTACT: ISetAsyncCall = {
  SET: SET_CONTACT,
};

export const SET_CONTACT_SELECTED = 'SET_CONTACT_SELECTED/SET';
export const ASYNC_SET_CONTACT_SELECTED: ISetAsyncCall = {
  SET: SET_CONTACT_SELECTED,
};

export const SHOW_MODAL_CONTACT = 'MODAL_CONTACT/SHOW';
export const HIDE_MODAL_CONTACT = 'MODAL_CONTACT/HIDE';
export const ASYNC_SHOW_MODAL_CONTACT: IModalAsyncCall = {
  SHOW: SHOW_MODAL_CONTACT,
  HIDE: HIDE_MODAL_CONTACT,
};
