/**
 * Images Defines
 * @author phuongpt
 */

export const IMAGES = {
  splash: require('~Root/assets/images/splash.png'),
  logo: require('~Root/assets/images/logo.png'),
  iconBackGreen: require('~Root/assets/images/back_arrow_green.png'),
  iconBackWhite: require('~Root/assets/images/back_arrow_white.png'),
  iconBackGrey: require('~Root/assets/images/back_arrow_grey.png'),
  iconNextWhite: require('~Root/assets/images/next_arrow_white.png'),
  iconEye: require('~Root/assets/images/icon_eye.png'),
  iconRobotBroken: require('~Root/assets/images/icon_robot_broken.png'),
  logo2: require('~Root/assets/images/logo2.png'),
  logoSmall: require('~Root/assets/images/logo_small.png'),
  logoDrawer: require('~Root/assets/images/logo_drawer.png'),
  iconLinkedin: require('~Root/assets/images/icon_linkedin.png'),
  iconPhone: require('~Root/assets/images/icon_phone.png'),
  onboard1: require('~Root/assets/images/onboard_1.png'),
  onboard2: require('~Root/assets/images/onboard_2.png'),
  onboard3: require('~Root/assets/images/onboard_3.png'),
  introBg: require('~Root/assets/images/intro_bg.png'),
  iconBurgerMenu: require('~Root/assets/images/icon_burger_menu.png'),
  iconBurgerMenuWhite: require('~Root/assets/images/icon_burger_menu_white.png'),
  iconCloseWhite: require('~Root/assets/images/icon_close_white.png'),
  iconCloseBlue: require('~Root/assets/images/icon_close_blue.png'),
  iconYourAsk: require('~Root/assets/images/icon_your_ask.png'),
  iconYourAskActive: require('~Root/assets/images/icon_your_ask_active.png'),
  iconAIRFeed: require('~Root/assets/images/icon_air_feed.png'),
  iconAIRFeedActive: require('~Root/assets/images/icon_air_feed_active.png'),
  iconAsk: require('~Root/assets/images/icon_ask.png'),
  iconTrustNetwork: require('~Root/assets/images/icon_trust_network.png'),
  iconTrustNetworkActive: require('~Root/assets/images/icon_trust_network_active.png'),
  iconChat: require('~Root/assets/images/icon_chat.png'),
  iconChatActive: require('~Root/assets/images/icon_chat_active.png'),
  iconAccount: require('~Root/assets/images/icon_account.png'),
  iconNotification: require('~Root/assets/images/icon_notification.png'),
  iconPrivacy: require('~Root/assets/images/icon_privacy.png'),
  iconHelp: require('~Root/assets/images/icon_help.png'),
  iconFeedback: require('~Root/assets/images/icon_feedback.png'),
  iconSetting: require('~Root/assets/images/icon_setting.png'),
  iconLogout: require('~Root/assets/images/icon_logout.png'),
  iconError: require('~Root/assets/images/icon_error.png'),
  iconSearch: require('~Root/assets/images/icon_search.png'),
  iconThreeDot: require('~Root/assets/images/icon_three_dot.png'),
  iconCalendar: require('~Root/assets/images/icon_calendar.png'),
  iconGlobe: require('~Root/assets/images/icon_globe.png'),
  iconVerify: require('~Root/assets/images/icon_verify.png'),
  iconPdf: require('~Root/assets/images/icon_pdf.png'),
  iconXls: require('~Root/assets/images/icon_xls.png'),
  dotPagination: require('~Root/assets/images/dot_pagination.png'),
  iconDropDown: require('~Root/assets/images/icon_dropdown.png'),
  iconCat: require('~Root/assets/images/cat.png'),
  iconCatNext: require('~Root/assets/images/cat_next.png'),
  iconCloseCircleWhite: require('~Root/assets/images/icon_close_circle_white.png'),
  iconGlobeEarth: require('~Root/assets/images/icon_globe_earth.png'),
  iconCalendarBlue: require('~Root/assets/images/icon_calendar_blue.png'),
  iconSubtract: require('~Root/assets/images/icon_subtract.png'),
};
