export const GET_ASK_REQUESTED = 'GET_ASK/REQUESTED';
export const GET_ASK_SUCCESS = 'GET_ASK/SUCCESS';
export const GET_ASK_FAILURE = 'GET_ASK/FAILURE';

export const GET_ASK_RESPONDER_REQUESTED = 'GET_ASK_RESPONDER/REQUESTED';
export const GET_ASK_RESPONDER_SUCCESS = 'GET_ASK_RESPONDER/SUCCESS';
export const GET_ASK_RESPONDER_FAILURE = 'GET_ASK_RESPONDER/FAILURE';

export const GET_ASK_EDIT_REQUESTED = 'GET_ASK_EDIT/REQUESTED';
export const GET_ASK_EDIT_SUCCESS = 'GET_ASK_EDIT/SUCCESS';
export const GET_ASK_EDIT_FAILURE = 'GET_ASK_EDIT/FAILURE';

export const CREATE_ASK_REQUESTED = 'CREATE_ASK/REQUESTED';
export const CREATE_ASK_SUCCESS = 'CREATE_ASK/SUCCESS';
export const CREATE_ASK_FAILURE = 'CREATE_ASK/FAILURE';

export const UPDATE_ASK_REQUESTED = 'UPDATE_ASK/REQUESTED';
export const UPDATE_ASK_SUCCESS = 'UPDATE_ASK/SUCCESS';
export const UPDATE_ASK_FAILURE = 'UPDATE_ASK/FAILURE';

export const GET_JOB_REQUESTED = 'GET_JOB/REQUESTED';
export const GET_JOB_SUCCESS = 'GET_JOB/SUCCESS';
export const GET_JOB_FAILURE = 'GET_JOB/FAILURE';

export const GET_LOCATION_REQUESTED = 'GET_LOCATION/REQUESTED';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION/SUCCESS';
export const GET_LOCATION_FAILURE = 'GET_LOCATION/FAILURE';

export const ON_UPDATE_EXTEND_DEADLINE_REQUESTED = 'ON_UPDATE_EXTEND_DEADLINE/REQUESTED';
export const ON_UPDATE_EXTEND_DEADLINE_SUCCESS = 'ON_UPDATE_EXTEND_DEADLINE/SUCCESS';
export const ON_UPDATE_EXTEND_DEADLINE_FAILURE = 'ON_UPDATE_EXTEND_DEADLINE/FAILURE';

export const ON_SEND_KUDOS_REQUESTED = 'ON_SEND_KUDOS/REQUESTED';
export const ON_SEND_KUDOS_SUCCESS = 'ON_SEND_KUDOS/SUCCESS';
export const ON_SEND_KUDOS_FAILURE = 'ON_SEND_KUDOS/FAILURE';

export const ON_END_ASK_REQUESTED = 'ON_END_ASK/REQUESTED';
export const ON_END_ASK_SUCCESS = 'ON_END_ASK/SUCCESS';
export const ON_END_ASK_FAILURE = 'ON_END_ASK/FAILURE';

export const SET_DATA_CREATE_ASK_STEP_1 = 'DATA_CREATE_ASK_STEP_1/SET';
export const SET_DATA_CREATE_ASK_STEP_2 = 'DATA_CREATE_ASK_STEP_2/SET';
export const SET_DATA_CREATE_ASK_STEP_3 = 'DATA_CREATE_ASK_STEP_3/SET';

export const SET_VISIBLE_MENU = 'VISIBLE_MENU/SET';

export const SET_LOCATION = 'LOCATION/SET';
