export const GET_ASK_REQUESTED = 'GET_ASK/REQUESTED';
export const GET_ASK_SUCCESS = 'GET_ASK/SUCCESS';
export const GET_ASK_FAILURE = 'GET_ASK/FAILURE';

export const GET_ASK_DETAILS_REQUESTED = 'GET_ASK_DETAILS/REQUESTED';
export const GET_ASK_DETAILS_SUCCESS = 'GET_ASK_DETAILS/SUCCESS';
export const GET_ASK_DETAILS_FAILURE = 'GET_ASK_DETAILS/FAILURE';

export const CREATE_ASK_REQUESTED = 'CREATE_ASK/REQUESTED';
export const CREATE_ASK_SUCCESS = 'CREATE_ASK/SUCCESS';
export const CREATE_ASK_FAILURE = 'CREATE_ASK/FAILURE';

export const UPDATE_ASK_REQUESTED = 'UPDATE_ASK/REQUESTED';
export const UPDATE_ASK_SUCCESS = 'UPDATE_ASK/SUCCESS';
export const UPDATE_ASK_FAILURE = 'UPDATE_ASK/FAILURE';

export const GET_JOB_REQUESTED = 'GET_JOB/REQUESTED';
export const GET_JOB_SUCCESS = 'GET_JOB/SUCCESS';
export const GET_JOB_FAILURE = 'GET_JOB/FAILURE';

export const GET_LOCATION_REQUESTED = 'GET_LOCATION/REQUESTED';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION/SUCCESS';
export const GET_LOCATION_FAILURE = 'GET_LOCATION/FAILURE';

export const SET_DATA_CREATE_ASK_STEP_1 = 'DATA_CREATE_ASK_STEP_1/SET';
export const SET_DATA_CREATE_ASK_STEP_2 = 'DATA_CREATE_ASK_STEP_2/SET';
export const SET_DATA_CREATE_ASK_STEP_3 = 'DATA_CREATE_ASK_STEP_3/SET';

export const SET_VISIBLE_MENU = 'VISIBLE_MENU/SET';

export const SET_LOCATION = 'LOCATION/SET';
