import {Platform, StyleSheet} from 'react-native';
import {BASE_COLORS, BASE_FONTS, BASE_STYLES, GlobalStyles} from '~Root/config';
import {adjust} from '~Root/utils';

export default StyleSheet.create({
  container: {
    backgroundColor: BASE_COLORS.whiteColor,
  },
  scrollView: {
    backgroundColor: BASE_COLORS.whiteColor,
    marginTop: 0,
    zIndex: -1,
    paddingTop: 0,
    flex: 1,
  },
  scrollViewContentContainer: {
    ...GlobalStyles.pb80,
  },
  contentContainer: {
    borderTopLeftRadius: adjust(22),
    marginTop: adjust(-20),
  },
  btn: {
    width: adjust(20),
    height: adjust(20),
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: adjust(5),
  },
  btnActive: {
    width: adjust(20),
    height: adjust(20),
    borderRadius: adjust(5),
  },
  dotPagination: {
    height: adjust(4),
    width: adjust(36),
  },
  styleTag: {
    borderTopLeftRadius: adjust(22),
    borderTopRightRadius: adjust(22),
    borderBottomLeftRadius: adjust(22),
    borderBottomRightRadius: adjust(22),
    backgroundColor: BASE_COLORS.steelBlue2Color,
    borderWidth: 0,
  },
  styleDropDown: {
    borderTopLeftRadius: adjust(22),
    borderTopRightRadius: adjust(22),
    borderBottomLeftRadius: adjust(22),
    borderBottomRightRadius: adjust(22),
    backgroundColor: BASE_COLORS.whiteColor,
  },
  styleButton: {
    borderTopLeftRadius: adjust(22),
    borderTopRightRadius: adjust(22),
    borderBottomLeftRadius: adjust(22),
    borderBottomRightRadius: adjust(22),
    backgroundColor: BASE_COLORS.steelBlue2Color,
    height: adjust(32),
  },
  tagContainer: {
    flexWrap: 'wrap',
  },
  tagText: {
    color: BASE_COLORS.whiteColor,
  },
  iconDropDown: {
    width: adjust(22),
    height: adjust(22),
  },
  buttonTextStyle: {
    ...GlobalStyles.p,
    color: BASE_COLORS.whiteColor,
    fontFamily: BASE_FONTS.semiBold,
    fontWeight: '600',
    textAlign: 'left',
  },
  iconCatContainer: {
    position: 'absolute',
    bottom: adjust(25),
    right: adjust(25),
  },
  iconCat: {
    width: adjust(55),
    height: adjust(45),
  },
  iconCatNext: {
    width: adjust(107),
    height: adjust(51),
  },
  tooltipStyle: {
    height: Platform.OS === 'ios' ? '25%' : '32%',
  },
  tooltipNetworkStyle: {
    height: '25%',
  },
  tooltipContentStyle: {
    ...GlobalStyles.p20,
    position: 'absolute',
    bottom: adjust(60),
    left: adjust(40),
    borderRadius: adjust(10),
    backgroundColor: BASE_COLORS.whiteColor,
    width: '60%',
    shadowColor: BASE_COLORS.blackColor,
    shadowOffset: {
      width: 0,
      height: adjust(5),
    },
    shadowOpacity: adjust(0.2),
    shadowRadius: adjust(5),
    elevation: adjust(2),
    zIndex: 1,
  },
  tooltipTitleColor: {
    fontFamily: BASE_FONTS.semiBold,
    fontSize: BASE_STYLES.h5,
    color: BASE_COLORS.antiFlashWhiteColor,
  },
  tooltipTextColor: {
    color: BASE_COLORS.antiFlashWhiteColor,
  },
  tooltipNetwork: {
    width: '90%',
  },
  tooltipCloseBtnContainer: {
    position: 'absolute',
    right: adjust(-48),
    top: adjust(-25),
  },
  textSmall: {
    fontSize: adjust(11),
  },
  iconCloseCircleWhite: {
    width: adjust(26),
    height: adjust(26),
  },
  inputContainer: {
    ...GlobalStyles.mt5,
    ...GlobalStyles.mb5,
    ...GlobalStyles.ph10,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'rgba(229, 229, 229, 0.46);',
    borderRadius: adjust(22),
    width: '70%',
    paddingVertical: Platform.OS === 'ios' ? adjust(10) : 0,
    alignItems: 'center',
    height: adjust(40),
  },
  inputAreaContainer: {
    ...GlobalStyles.mt5,
    ...GlobalStyles.ph10,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'rgba(229, 229, 229, 0.46);',
    borderRadius: adjust(22),
    width: '100%',
    height: adjust(150),
    paddingVertical: Platform.OS === 'ios' ? adjust(10) : 0,
    alignItems: 'flex-start',
    borderColor: BASE_COLORS.steelBlue2Color,
    borderWidth: 1,
  },
  input: {
    ...GlobalStyles.p,
    flex: 1,
    lineHeight: adjust(15),
    color: BASE_COLORS.gunmetalColor,
  },
  inputArea: {
    ...GlobalStyles.p,
    flex: 1,
    width: '100%',
    lineHeight: adjust(15),
    color: BASE_COLORS.gunmetalColor,
    height: '100%',
  },
  inputDynamicContainer: {
    ...GlobalStyles.mb5,
    ...GlobalStyles.ph10,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: BASE_COLORS.steelBlue2Color,
    borderColor: BASE_COLORS.steelBlue2Color,
    borderRadius: adjust(22),
    paddingVertical: Platform.OS === 'ios' ? adjust(10) : 0,
    alignItems: 'center',
    height: adjust(35),
    alignSelf: 'flex-start',
    maxWidth: '100%',
    overflow: 'hidden',
  },
  inputDynamicActiveContainer: {
    ...GlobalStyles.mb5,
    ...GlobalStyles.ph10,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'rgba(229, 229, 229, 0.46);',
    borderColor: BASE_COLORS.steelBlue2Color,
    borderRadius: adjust(22),
    paddingVertical: Platform.OS === 'ios' ? adjust(10) : 0,
    justifyContent: 'center',
    alignItems: 'center',
    height: adjust(35),
    alignSelf: 'flex-start',
    maxWidth: '100%',
    overflow: 'hidden',
  },
  textAreaDynamicContainer: {
    ...GlobalStyles.mb5,
    ...GlobalStyles.ph10,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: BASE_COLORS.steelBlue2Color,
    borderColor: BASE_COLORS.steelBlue2Color,
    borderRadius: adjust(22),
    paddingVertical: Platform.OS === 'ios' ? adjust(5) : 0,
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: '100%',
    overflow: 'hidden',
    height: 'auto',
  },
  textAreaDynamicActiveContainer: {
    ...GlobalStyles.mb5,
    ...GlobalStyles.ph10,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'rgba(229, 229, 229, 0.46);',
    borderColor: BASE_COLORS.steelBlue2Color,
    borderRadius: adjust(22),
    paddingVertical: Platform.OS === 'ios' ? adjust(8) : 0,
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: '100%',
    overflow: 'hidden',
    height: 'auto',
  },
  inputMinWidth: {
    minWidth: adjust(30),
  },
  inputStyle: {
    flex: 1,
    fontFamily: BASE_FONTS.semiBold,
    fontWeight: '600',
    color: BASE_COLORS.whiteColor,
    maxWidth: '100%',
  },
  inputActiveStyle: {
    flex: 1,
    fontFamily: BASE_FONTS.semiBold,
    fontWeight: '600',
    color: BASE_COLORS.steelBlue2Color,
    maxWidth: '100%',
  },
  placeholderTextInputStyle: {
    fontFamily: BASE_FONTS.semiBold,
    fontWeight: '600',
    color: BASE_COLORS.whiteColor,
    lineHeight: adjust(12),
  },
  placeholderTextInputActiveStyle: {
    fontFamily: BASE_FONTS.semiBold,
    fontWeight: '600',
    color: BASE_COLORS.steelBlue2Color,
    lineHeight: adjust(12),
  },
  placeholderTextAreaStyle: {
    fontFamily: BASE_FONTS.semiBold,
    fontWeight: '600',
    color: BASE_COLORS.whiteColor,
    lineHeight: adjust(20),
  },
  placeholderTextAreaActiveStyle: {
    fontFamily: BASE_FONTS.semiBold,
    fontWeight: '600',
    color: BASE_COLORS.steelBlue2Color,
    lineHeight: adjust(20),
  },
  borderTop: {
    borderTopWidth: 1,
    borderColor: BASE_COLORS.darkGray,
  },
  btnGreetings: {
    borderWidth: 1,
    borderColor: BASE_COLORS.steelBlue2Color,
    borderRadius: adjust(22),
  },
  iconTriangle: {
    position: 'absolute',
    bottom: adjust(-10),
    right: adjust(-28),
    shadowColor: BASE_COLORS.whiteColor,
    shadowOffset: {
      width: 0,
      height: adjust(5),
    },
    shadowOpacity: adjust(0.2),
    shadowRadius: adjust(5),
    elevation: adjust(2),
  },
  btnMain: {
    backgroundColor: BASE_COLORS.forestGreenColor,
    position: 'absolute',
    top: adjust(21),
    zIndex: 0,
    width: adjust(79),
    borderRadius: adjust(20),
  },
});
