export const LOGIN_REQUESTED = 'LOGIN/REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS';
export const LOGIN_FAILURE = 'LOGIN/FAILURE';

export const FORGOT_PASSWORD_REQUESTED = 'FORGOT_PASSWORD/REQUESTED';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD/SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD/FAILURE';
