import {IAsyncCall} from '~Root/types';

export const LIST_MATCHES_REQUESTED = 'LIST_MATCHES/REQUESTED';
export const LIST_MATCHES_SUCCESS = 'LIST_MATCHES/SUCCESS';
export const LIST_MATCHES_FAILURE = 'LIST_MATCHES/FAILURE';

export const ASYNC_LIST_MATCHES: IAsyncCall = {
  REQUESTED: LIST_MATCHES_REQUESTED,
  SUCCESS: LIST_MATCHES_SUCCESS,
  FAILURE: LIST_MATCHES_FAILURE,
};
