export const GET_CHAT_CONTEXT_REQUESTED = 'GET_CHAT_CONTEXT/REQUESTED';
export const GET_CHAT_CONTEXT_SUCCESS = 'GET_CHAT_CONTEXT/SUCCESS';
export const GET_CHAT_CONTEXT_FAILURE = 'GET_CHAT_CONTEXT/FAILURE';

export const ON_PIN_REQUESTED = 'ON_PIN/REQUESTED';
export const ON_PIN_SUCCESS = 'ON_PIN/SUCCESS';
export const ON_PIN_FAILURE = 'ON_PIN/FAILURE';

export const ON_UN_PIN_REQUESTED = 'ON_UN_PIN/REQUESTED';
export const ON_UN_PIN_SUCCESS = 'ON_UN_PIN/SUCCESS';
export const ON_UN_PIN_FAILURE = 'ON_UN_PIN/FAILURE';

export const GET_USER_CHAT_LIST_REQUESTED = 'GET_USER_CHAT_LIST/REQUESTED';
export const GET_USER_CHAT_LIST_SUCCESS = 'GET_USER_CHAT_LIST/SUCCESS';
export const GET_USER_CHAT_LIST_FAILURE = 'GET_USER_CHAT_LIST/FAILURE';

export const GET_CHAT_FEED_REQUESTED = 'GET_CHAT_FEED/REQUESTED';
export const GET_CHAT_FEED_SUCCESS = 'GET_CHAT_FEED/SUCCESS';
export const GET_CHAT_FEED_FAILURE = 'GET_CHAT_FEED/FAILURE';

export const SET_CHAT_VISIBLE_MENU = 'CHAT_VISIBLE_MENU/SET';
