export enum AppRoute {
  SPLASH = 'Splash',
  APP_CHECK = 'AppCheck',
  HOME = 'Home',
  HOME_DETAIL = 'HomeDetail',
  LOGIN = 'Login',
  INVITE_CODE = 'InviteCode',
  INVITE_CONFIRM = 'InviteConfirm',
  INVITE_EXPIRE = 'InviteExpire',
  REGISTER = 'Register',
  RESET_PASSWORD = 'ResetPassword',
  FORGOT_PASSWORD = 'ForgotPassword',
  PROFILE = 'Profile',
  PROFILE_SECOND = 'ProfileSecond',
  CHAT = 'Chat',
  CHAT_INTERNAL = 'ChatInternal',
  CHAT_CONTEXT_SWITCH = 'ChatContextSwitch',
  CHAT_NOTIFICATION_ASKER = 'ChatNotificationAsker',
  VIEW_PARTICIPANT = 'ViewParticipant',
  AIR_FEED = 'AIRFeed',
  TABS = 'Tabs',
  CREATE_ASK = 'CreateAsk',
  ASK_PREVIEW = 'AskPreview',
  ASK_PUBLISH = 'AskPublish',
  VERIFY_EMAIL = 'VerifyEmail',
  VERIFIED_EMAIL = 'VerifiedEmail',
  RECOVER_PASSWORD = 'RecoverPassword',
  HOME_SHARE_SCREEN = 'HomeShare',
  ON_BOARDING_SCREEN = 'Onboarding',
  PROFILE_PERSONAL = 'ProfilePersonal',
  PROFILE_INDUSTRY = 'ProfileIndustry',
  INVITE_CONTACT = 'InviteContact',
  INVITE_CONTACT_EDIT = 'InviteContactEdit',
  MAIN_DRAWER = 'MainDrawer',
  LIST_CONTACT = 'ListContact',
  SEND_INVITES = 'SendInvites',
  FEED_BACK_MODAL = 'FeedBackModal',
  INDIVIDUAL_MESSAGE_MODAL = 'IndividualMessageModal',
  JOINT_MESSAGE_MODAL = 'JointMessageModal',
}

export const AppRouteNotTabBar = {
  PROFILE_SECOND: 'ProfileSecond',
};
