export const GET_FEED_ITEMS_LIST_REQUESTED = 'GET_FEED_ITEMS_LIST/REQUESTED';
export const GET_FEED_ITEMS_LIST_SUCCESS = 'GET_FEED_ITEMS_LIST/SUCCESS';
export const GET_FEED_ITEMS_LIST_FAILURE = 'GET_FEED_ITEMS_LIST/FAILURE';

export const GET_FEED_ITEM_PAGINATION_REQUESTED = 'GET_FEED_ITEM_PAGINATION/REQUESTED';
export const GET_FEED_ITEM_PAGINATION_SUCCESS = 'GET_FEED_ITEM_PAGINATION/SUCCESS';
export const GET_FEED_ITEM_PAGINATION_FAILURE = 'GET_FEED_ITEM_PAGINATION/FAILURE';

export const SET_FEED_ITEM_READ_REQUESTED = 'SET_FEED_ITEM_READ/REQUESTED';
export const SET_FEED_ITEM_READ_SUCCESS = 'SET_FEED_ITEM_READ/SUCCESS';
export const SET_FEED_ITEM_READ_FAILURE = 'SET_FEED_ITEM_READ/FAILURE';

export const SET_FEED_VISIBLE_MENU = 'FEED_VISIBLE_MENU/SET';
