export const GET_FEED_ITEMS_LIST_REQUESTED = 'GET_FEED_ITEMS_LIST/REQUESTED';
export const GET_FEED_ITEMS_LIST_SUCCESS = 'GET_FEED_ITEMS_LIST/SUCCESS';
export const GET_FEED_ITEMS_LIST_FAILURE = 'GET_FEED_ITEMS_LIST/FAILURE';

export const GET_FEED_ITEM_PAGINATION_REQUESTED = 'GET_FEED_ITEM_PAGINATION/REQUESTED';
export const GET_FEED_ITEM_PAGINATION_SUCCESS = 'GET_FEED_ITEM_PAGINATION/SUCCESS';
export const GET_FEED_ITEM_PAGINATION_FAILURE = 'GET_FEED_ITEM_PAGINATION/FAILURE';
