export const GET_ASK_DETAILS_REQUESTED = 'GET_ASK_DETAILS/REQUESTED';
export const GET_ASK_DETAILS_SUCCESS = 'GET_ASK_DETAILS/SUCCESS';
export const GET_ASK_DETAILS_FAILURE = 'GET_ASK_DETAILS/FAILURE';

export const SET_ASK_DETAILS = 'ASK_DETAILS/SET';
